name: Testing Secret Variables

on: 
  workflow_dispatch

env:
     ACTIONS_STEP_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
      - name: checking secret variable
        run: |
          echo "secret value : ${{secrets.MY_KEY}}"
          ${{secrets.MY_KEY}}
